<?xml version="1.0" encoding="UTF-8"?><testsuite name="nosetests" tests="8" errors="0" failures="8" skip="0"><testcase classname="testsuite.test_get.TestGet" name="test_gets_0_acquirer" time="0.858"><failure type="exceptions.AssertionError" message='404 != 200&#10;-------------------- &gt;&gt; begin captured logging &lt;&lt; --------------------&#10;api_testsuite: INFO: Testcase test_gets_0_acquirer Started at 1556549867.29&#10;api_testsuite: INFO: test_gets_0_acquirer STARTED&#10;api_testsuite: INFO: #. Test using GET path /acquirer, should succeed&#10;api_testsuite: INFO: GET http://10.63.30.144:9002/v1/acquirer&#10;urllib3.connectionpool: INFO: Starting new HTTP connection (1): hybrid-web.global.blackspider.com&#10;urllib3.connectionpool: DEBUG: Setting read timeout to 30&#10;urllib3.connectionpool: DEBUG: "GET http://10.63.30.144:9002/v1/acquirer HTTP/1.1" 404 None&#10;--------------------- &gt;&gt; end captured logging &lt;&lt; ---------------------'><![CDATA[  File "/usr/lib/python2.7/unittest/case.py", line 331, in run
    testMethod()
  File "/usr/local/lib/python2.7/dist-packages/parameterized/parameterized.py", line 518, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "/home/osboxes/Downloads/repos/api-testing/Python/apitesting/testsuite/test_get.py", line 36, in test_gets
    self.assertEqual(response.status_code, 200)
  File "/usr/lib/python2.7/unittest/case.py", line 515, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib/python2.7/unittest/case.py", line 508, in _baseAssertEqual
    raise self.failureException(msg)
'404 != 200\n-------------------- >> begin captured logging << --------------------\napi_testsuite: INFO: Testcase test_gets_0_acquirer Started at 1556549867.29\napi_testsuite: INFO: test_gets_0_acquirer STARTED\napi_testsuite: INFO: #. Test using GET path /acquirer, should succeed\napi_testsuite: INFO: GET http://10.63.30.144:9002/v1/acquirer\nurllib3.connectionpool: INFO: Starting new HTTP connection (1): hybrid-web.global.blackspider.com\nurllib3.connectionpool: DEBUG: Setting read timeout to 30\nurllib3.connectionpool: DEBUG: "GET http://10.63.30.144:9002/v1/acquirer HTTP/1.1" 404 None\n--------------------- >> end captured logging << ---------------------']]></failure></testcase><testcase classname="testsuite.test_get.TestGet" name="test_gets_1_acquirer_acquirer_id_2" time="0.020"><failure type="exceptions.AssertionError" message='404 != 200&#10;-------------------- &gt;&gt; begin captured logging &lt;&lt; --------------------&#10;api_testsuite: INFO: Testcase test_gets_1_acquirer_acquirer_id_2 Started at 1556549868.15&#10;api_testsuite: INFO: test_gets_1_acquirer_acquirer_id_2 STARTED&#10;api_testsuite: INFO: #. Test using GET path /acquirer?acquirer_id=2, should succeed&#10;api_testsuite: INFO: GET http://10.63.30.144:9002/v1/acquirer?acquirer_id=2&#10;urllib3.connectionpool: INFO: Starting new HTTP connection (1): hybrid-web.global.blackspider.com&#10;urllib3.connectionpool: DEBUG: Setting read timeout to 30&#10;urllib3.connectionpool: DEBUG: "GET http://10.63.30.144:9002/v1/acquirer?acquirer_id=2 HTTP/1.1" 404 None&#10;--------------------- &gt;&gt; end captured logging &lt;&lt; ---------------------'><![CDATA[  File "/usr/lib/python2.7/unittest/case.py", line 331, in run
    testMethod()
  File "/usr/local/lib/python2.7/dist-packages/parameterized/parameterized.py", line 518, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "/home/osboxes/Downloads/repos/api-testing/Python/apitesting/testsuite/test_get.py", line 36, in test_gets
    self.assertEqual(response.status_code, 200)
  File "/usr/lib/python2.7/unittest/case.py", line 515, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib/python2.7/unittest/case.py", line 508, in _baseAssertEqual
    raise self.failureException(msg)
'404 != 200\n-------------------- >> begin captured logging << --------------------\napi_testsuite: INFO: Testcase test_gets_1_acquirer_acquirer_id_2 Started at 1556549868.15\napi_testsuite: INFO: test_gets_1_acquirer_acquirer_id_2 STARTED\napi_testsuite: INFO: #. Test using GET path /acquirer?acquirer_id=2, should succeed\napi_testsuite: INFO: GET http://10.63.30.144:9002/v1/acquirer?acquirer_id=2\nurllib3.connectionpool: INFO: Starting new HTTP connection (1): hybrid-web.global.blackspider.com\nurllib3.connectionpool: DEBUG: Setting read timeout to 30\nurllib3.connectionpool: DEBUG: "GET http://10.63.30.144:9002/v1/acquirer?acquirer_id=2 HTTP/1.1" 404 None\n--------------------- >> end captured logging << ---------------------']]></failure></testcase><testcase classname="testsuite.test_get.TestGet" name="test_gets_2_acquirer_offset_1" time="0.021"><failure type="exceptions.AssertionError" message='404 != 200&#10;-------------------- &gt;&gt; begin captured logging &lt;&lt; --------------------&#10;api_testsuite: INFO: Testcase test_gets_2_acquirer_offset_1 Started at 1556549868.17&#10;api_testsuite: INFO: test_gets_2_acquirer_offset_1 STARTED&#10;api_testsuite: INFO: #. Test using GET path /acquirer?offset=1, should succeed&#10;api_testsuite: INFO: GET http://10.63.30.144:9002/v1/acquirer?offset=1&#10;urllib3.connectionpool: INFO: Starting new HTTP connection (1): hybrid-web.global.blackspider.com&#10;urllib3.connectionpool: DEBUG: Setting read timeout to 30&#10;urllib3.connectionpool: DEBUG: "GET http://10.63.30.144:9002/v1/acquirer?offset=1 HTTP/1.1" 404 None&#10;--------------------- &gt;&gt; end captured logging &lt;&lt; ---------------------'><![CDATA[  File "/usr/lib/python2.7/unittest/case.py", line 331, in run
    testMethod()
  File "/usr/local/lib/python2.7/dist-packages/parameterized/parameterized.py", line 518, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "/home/osboxes/Downloads/repos/api-testing/Python/apitesting/testsuite/test_get.py", line 36, in test_gets
    self.assertEqual(response.status_code, 200)
  File "/usr/lib/python2.7/unittest/case.py", line 515, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib/python2.7/unittest/case.py", line 508, in _baseAssertEqual
    raise self.failureException(msg)
'404 != 200\n-------------------- >> begin captured logging << --------------------\napi_testsuite: INFO: Testcase test_gets_2_acquirer_offset_1 Started at 1556549868.17\napi_testsuite: INFO: test_gets_2_acquirer_offset_1 STARTED\napi_testsuite: INFO: #. Test using GET path /acquirer?offset=1, should succeed\napi_testsuite: INFO: GET http://10.63.30.144:9002/v1/acquirer?offset=1\nurllib3.connectionpool: INFO: Starting new HTTP connection (1): hybrid-web.global.blackspider.com\nurllib3.connectionpool: DEBUG: Setting read timeout to 30\nurllib3.connectionpool: DEBUG: "GET http://10.63.30.144:9002/v1/acquirer?offset=1 HTTP/1.1" 404 None\n--------------------- >> end captured logging << ---------------------']]></failure></testcase><testcase classname="testsuite.test_get.TestGet" name="test_gets_3_acquirer_limit_1" time="0.022"><failure type="exceptions.AssertionError" message='404 != 200&#10;-------------------- &gt;&gt; begin captured logging &lt;&lt; --------------------&#10;api_testsuite: INFO: Testcase test_gets_3_acquirer_limit_1 Started at 1556549868.19&#10;api_testsuite: INFO: test_gets_3_acquirer_limit_1 STARTED&#10;api_testsuite: INFO: #. Test using GET path /acquirer?limit=1, should succeed&#10;api_testsuite: INFO: GET http://10.63.30.144:9002/v1/acquirer?limit=1&#10;urllib3.connectionpool: INFO: Starting new HTTP connection (1): hybrid-web.global.blackspider.com&#10;urllib3.connectionpool: DEBUG: Setting read timeout to 30&#10;urllib3.connectionpool: DEBUG: "GET http://10.63.30.144:9002/v1/acquirer?limit=1 HTTP/1.1" 404 None&#10;--------------------- &gt;&gt; end captured logging &lt;&lt; ---------------------'><![CDATA[  File "/usr/lib/python2.7/unittest/case.py", line 331, in run
    testMethod()
  File "/usr/local/lib/python2.7/dist-packages/parameterized/parameterized.py", line 518, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "/home/osboxes/Downloads/repos/api-testing/Python/apitesting/testsuite/test_get.py", line 36, in test_gets
    self.assertEqual(response.status_code, 200)
  File "/usr/lib/python2.7/unittest/case.py", line 515, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib/python2.7/unittest/case.py", line 508, in _baseAssertEqual
    raise self.failureException(msg)
'404 != 200\n-------------------- >> begin captured logging << --------------------\napi_testsuite: INFO: Testcase test_gets_3_acquirer_limit_1 Started at 1556549868.19\napi_testsuite: INFO: test_gets_3_acquirer_limit_1 STARTED\napi_testsuite: INFO: #. Test using GET path /acquirer?limit=1, should succeed\napi_testsuite: INFO: GET http://10.63.30.144:9002/v1/acquirer?limit=1\nurllib3.connectionpool: INFO: Starting new HTTP connection (1): hybrid-web.global.blackspider.com\nurllib3.connectionpool: DEBUG: Setting read timeout to 30\nurllib3.connectionpool: DEBUG: "GET http://10.63.30.144:9002/v1/acquirer?limit=1 HTTP/1.1" 404 None\n--------------------- >> end captured logging << ---------------------']]></failure></testcase><testcase classname="testsuite.test_get.TestGet" name="test_gets_4_bank" time="0.028"><failure type="exceptions.AssertionError" message='404 != 200&#10;-------------------- &gt;&gt; begin captured logging &lt;&lt; --------------------&#10;api_testsuite: INFO: Testcase test_gets_4_bank Started at 1556549868.21&#10;api_testsuite: INFO: test_gets_4_bank STARTED&#10;api_testsuite: INFO: #. Test using GET path /bank, should succeed&#10;api_testsuite: INFO: GET http://10.63.30.144:9002/v1/bank&#10;urllib3.connectionpool: INFO: Starting new HTTP connection (1): hybrid-web.global.blackspider.com&#10;urllib3.connectionpool: DEBUG: Setting read timeout to 30&#10;urllib3.connectionpool: DEBUG: "GET http://10.63.30.144:9002/v1/bank HTTP/1.1" 404 None&#10;--------------------- &gt;&gt; end captured logging &lt;&lt; ---------------------'><![CDATA[  File "/usr/lib/python2.7/unittest/case.py", line 331, in run
    testMethod()
  File "/usr/local/lib/python2.7/dist-packages/parameterized/parameterized.py", line 518, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "/home/osboxes/Downloads/repos/api-testing/Python/apitesting/testsuite/test_get.py", line 36, in test_gets
    self.assertEqual(response.status_code, 200)
  File "/usr/lib/python2.7/unittest/case.py", line 515, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib/python2.7/unittest/case.py", line 508, in _baseAssertEqual
    raise self.failureException(msg)
'404 != 200\n-------------------- >> begin captured logging << --------------------\napi_testsuite: INFO: Testcase test_gets_4_bank Started at 1556549868.21\napi_testsuite: INFO: test_gets_4_bank STARTED\napi_testsuite: INFO: #. Test using GET path /bank, should succeed\napi_testsuite: INFO: GET http://10.63.30.144:9002/v1/bank\nurllib3.connectionpool: INFO: Starting new HTTP connection (1): hybrid-web.global.blackspider.com\nurllib3.connectionpool: DEBUG: Setting read timeout to 30\nurllib3.connectionpool: DEBUG: "GET http://10.63.30.144:9002/v1/bank HTTP/1.1" 404 None\n--------------------- >> end captured logging << ---------------------']]></failure></testcase><testcase classname="testsuite.test_get.TestGet" name="test_gets_5_bank_bank_id_501" time="0.025"><failure type="exceptions.AssertionError" message='404 != 200&#10;-------------------- &gt;&gt; begin captured logging &lt;&lt; --------------------&#10;api_testsuite: INFO: Testcase test_gets_5_bank_bank_id_501 Started at 1556549868.24&#10;api_testsuite: INFO: test_gets_5_bank_bank_id_501 STARTED&#10;api_testsuite: INFO: #. Test using GET path /bank?bank_id=501, should succeed&#10;api_testsuite: INFO: GET http://10.63.30.144:9002/v1/bank?bank_id=501&#10;urllib3.connectionpool: INFO: Starting new HTTP connection (1): hybrid-web.global.blackspider.com&#10;urllib3.connectionpool: DEBUG: Setting read timeout to 30&#10;urllib3.connectionpool: DEBUG: "GET http://10.63.30.144:9002/v1/bank?bank_id=501 HTTP/1.1" 404 None&#10;--------------------- &gt;&gt; end captured logging &lt;&lt; ---------------------'><![CDATA[  File "/usr/lib/python2.7/unittest/case.py", line 331, in run
    testMethod()
  File "/usr/local/lib/python2.7/dist-packages/parameterized/parameterized.py", line 518, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "/home/osboxes/Downloads/repos/api-testing/Python/apitesting/testsuite/test_get.py", line 36, in test_gets
    self.assertEqual(response.status_code, 200)
  File "/usr/lib/python2.7/unittest/case.py", line 515, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib/python2.7/unittest/case.py", line 508, in _baseAssertEqual
    raise self.failureException(msg)
'404 != 200\n-------------------- >> begin captured logging << --------------------\napi_testsuite: INFO: Testcase test_gets_5_bank_bank_id_501 Started at 1556549868.24\napi_testsuite: INFO: test_gets_5_bank_bank_id_501 STARTED\napi_testsuite: INFO: #. Test using GET path /bank?bank_id=501, should succeed\napi_testsuite: INFO: GET http://10.63.30.144:9002/v1/bank?bank_id=501\nurllib3.connectionpool: INFO: Starting new HTTP connection (1): hybrid-web.global.blackspider.com\nurllib3.connectionpool: DEBUG: Setting read timeout to 30\nurllib3.connectionpool: DEBUG: "GET http://10.63.30.144:9002/v1/bank?bank_id=501 HTTP/1.1" 404 None\n--------------------- >> end captured logging << ---------------------']]></failure></testcase><testcase classname="testsuite.test_get.TestGet" name="test_gets_6_bank_offset_1" time="0.022"><failure type="exceptions.AssertionError" message='404 != 200&#10;-------------------- &gt;&gt; begin captured logging &lt;&lt; --------------------&#10;api_testsuite: INFO: Testcase test_gets_6_bank_offset_1 Started at 1556549868.27&#10;api_testsuite: INFO: test_gets_6_bank_offset_1 STARTED&#10;api_testsuite: INFO: #. Test using GET path /bank?offset=1, should succeed&#10;api_testsuite: INFO: GET http://10.63.30.144:9002/v1/bank?offset=1&#10;urllib3.connectionpool: INFO: Starting new HTTP connection (1): hybrid-web.global.blackspider.com&#10;urllib3.connectionpool: DEBUG: Setting read timeout to 30&#10;urllib3.connectionpool: DEBUG: "GET http://10.63.30.144:9002/v1/bank?offset=1 HTTP/1.1" 404 None&#10;--------------------- &gt;&gt; end captured logging &lt;&lt; ---------------------'><![CDATA[  File "/usr/lib/python2.7/unittest/case.py", line 331, in run
    testMethod()
  File "/usr/local/lib/python2.7/dist-packages/parameterized/parameterized.py", line 518, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "/home/osboxes/Downloads/repos/api-testing/Python/apitesting/testsuite/test_get.py", line 36, in test_gets
    self.assertEqual(response.status_code, 200)
  File "/usr/lib/python2.7/unittest/case.py", line 515, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib/python2.7/unittest/case.py", line 508, in _baseAssertEqual
    raise self.failureException(msg)
'404 != 200\n-------------------- >> begin captured logging << --------------------\napi_testsuite: INFO: Testcase test_gets_6_bank_offset_1 Started at 1556549868.27\napi_testsuite: INFO: test_gets_6_bank_offset_1 STARTED\napi_testsuite: INFO: #. Test using GET path /bank?offset=1, should succeed\napi_testsuite: INFO: GET http://10.63.30.144:9002/v1/bank?offset=1\nurllib3.connectionpool: INFO: Starting new HTTP connection (1): hybrid-web.global.blackspider.com\nurllib3.connectionpool: DEBUG: Setting read timeout to 30\nurllib3.connectionpool: DEBUG: "GET http://10.63.30.144:9002/v1/bank?offset=1 HTTP/1.1" 404 None\n--------------------- >> end captured logging << ---------------------']]></failure></testcase><testcase classname="testsuite.test_get.TestGet" name="test_gets_7_bank_limit_1" time="0.017"><failure type="exceptions.AssertionError" message='404 != 200&#10;-------------------- &gt;&gt; begin captured logging &lt;&lt; --------------------&#10;api_testsuite: INFO: Testcase test_gets_7_bank_limit_1 Started at 1556549868.29&#10;api_testsuite: INFO: test_gets_7_bank_limit_1 STARTED&#10;api_testsuite: INFO: #. Test using GET path /bank?limit=1, should succeed&#10;api_testsuite: INFO: GET http://10.63.30.144:9002/v1/bank?limit=1&#10;urllib3.connectionpool: INFO: Starting new HTTP connection (1): hybrid-web.global.blackspider.com&#10;urllib3.connectionpool: DEBUG: Setting read timeout to 30&#10;urllib3.connectionpool: DEBUG: "GET http://10.63.30.144:9002/v1/bank?limit=1 HTTP/1.1" 404 None&#10;--------------------- &gt;&gt; end captured logging &lt;&lt; ---------------------'><![CDATA[  File "/usr/lib/python2.7/unittest/case.py", line 331, in run
    testMethod()
  File "/usr/local/lib/python2.7/dist-packages/parameterized/parameterized.py", line 518, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "/home/osboxes/Downloads/repos/api-testing/Python/apitesting/testsuite/test_get.py", line 36, in test_gets
    self.assertEqual(response.status_code, 200)
  File "/usr/lib/python2.7/unittest/case.py", line 515, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib/python2.7/unittest/case.py", line 508, in _baseAssertEqual
    raise self.failureException(msg)
'404 != 200\n-------------------- >> begin captured logging << --------------------\napi_testsuite: INFO: Testcase test_gets_7_bank_limit_1 Started at 1556549868.29\napi_testsuite: INFO: test_gets_7_bank_limit_1 STARTED\napi_testsuite: INFO: #. Test using GET path /bank?limit=1, should succeed\napi_testsuite: INFO: GET http://10.63.30.144:9002/v1/bank?limit=1\nurllib3.connectionpool: INFO: Starting new HTTP connection (1): hybrid-web.global.blackspider.com\nurllib3.connectionpool: DEBUG: Setting read timeout to 30\nurllib3.connectionpool: DEBUG: "GET http://10.63.30.144:9002/v1/bank?limit=1 HTTP/1.1" 404 None\n--------------------- >> end captured logging << ---------------------']]></failure></testcase></testsuite>